name = "Jarod Wright"
description = "Developer"
keywords = ""
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://jarodwr.github.io"

[[sections]]
title = "Contact Details"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Mobile Number"
description = "(+61)403436298"
[[sections.items]]
title = "Email Address"
description = "wrjarod@gmail.com"

[[sections]]
title = "Links"
direction = "column"
item_style = "filled"
[[sections.items]]
title = "Github"
url = "https://www.github.com/Jarodwr"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/great.jaggi/"
[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/jarod-wright/"
